const merchantCountries = [
  {
    country: "Cameroon",
    dialing_code: "237",
    code: "cm",
    flag: "https://flagsapi.com/CM/flat/64.png",
    currency: {
      sign: "XAF",
      short: "FCFA",
      long: "CFA Franc",
      description: "Central African CFA Franc",
    },
  },
  {
    country: "Canada",
    dialing_code: "1",
    code: "ca",
    flag: "https://flagsapi.com/CA/flat/64.png",
    currency: {
      sign: "$",
      short: "CAD",
      long: "Dollar",
      description: "Canadian Dollar",
    },
  },
  {
    country: "Egypt",
    dialing_code: "20",
    code: "eg",
    flag: "https://flagsapi.com/EG/flat/64.png",
    currency: {
      sign: "£",
      short: "EGP",
      long: "Pound",
      description: "Egyptian Pound",
    },
  },
  {
    country: "France",
    dialing_code: "33",
    code: "fr",
    flag: "https://flagsapi.com/FR/flat/64.png",
    currency: {
      sign: "€",
      short: "EUR",
      long: "Euro",
      description: "Euro",
    },
  },
  {
    country: "Germany",
    dialing_code: "49",
    code: "de",
    flag: "https://flagsapi.com/DE/flat/64.png",
    currency: {
      sign: "€",
      short: "EUR",
      long: "Euro",
      description: "Euro",
    },
  },
  {
    country: "Ghana",
    dialing_code: "233",
    code: "gh",
    flag: "https://flagsapi.com/GH/flat/64.png",
    currency: {
      sign: "GH₵",
      short: "GHS",
      long: "Cedi",
      description: "Ghanaian Cedi",
    },
  },
  {
    country: "Ivory Coast",
    dialing_code: "225",
    code: "ci",
    flag: "https://flagsapi.com/CI/flat/64.png",
    currency: {
      sign: "CFA",
      short: "XOF",
      long: "CFA franc",
      description: "West African CFA franc",
    },
  },
  {
    country: "Kenya",
    dialing_code: "254",
    code: "ke",
    flag: "https://flagsapi.com/KE/flat/64.png",
    currency: {
      sign: "KSh",
      short: "KES",
      long: "Shilling",
      description: "Kenyan Shilling",
    },
  },
  {
    country: "Morocco",
    dialing_code: "212",
    code: "ma",
    flag: "https://flagsapi.com/MA/flat/64.png",
    currency: {
      sign: "د.م.",
      short: "MAD",
      long: "Dirham",
      description: "Moroccan Dirham",
    },
  },
  {
    country: "Netherlands",
    dialing_code: "31",
    code: "nl",
    flag: "https://flagsapi.com/NL/flat/64.png",
    currency: {
      sign: "€",
      short: "EUR",
      long: "Euro",
      description: "Euro",
    },
  },
  {
    country: "Nigeria",
    dialing_code: "234",
    code: "ng",
    flag: "https://flagsapi.com/NG/flat/64.png",
    currency: {
      sign: "₦",
      short: "NGN",
      long: "Naira",
      description: "Nigerian Naira",
    },
  },
  {
    country: "Portugal",
    dialing_code: "351",
    code: "pt",
    flag: "https://flagsapi.com/PT/flat/64.png",
    currency: {
      sign: "€",
      short: "EUR",
      long: "Euro",
      description: "Euro",
    },
  },
  {
    country: "Republic of the Congo",
    dialing_code: "242",
    code: "cg",
    flag: "https://flagsapi.com/CG/flat/64.png",
    currency: {
      sign: "FC",
      short: "XAF",
      long: "CFA franc",
      description: "Central African CFA franc",
    },
  },
  {
    country: "Rwanda",
    dialing_code: "250",
    code: "rw",
    flag: "https://flagsapi.com/RW/flat/64.png",
    currency: {
      sign: "RWF",
      short: "RWF",
      long: "franc",
      description: "Rwandan franc",
    },
  },
  {
    country: "Senegal",
    dialing_code: "221",
    code: "sn",
    flag: "https://flagsapi.com/SN/flat/64.png",
    currency: {
      sign: "CFA",
      short: "XOF",
      long: "CFA franc",
      description: "West African CFA franc",
    },
  },
  {
    country: "South Africa",
    dialing_code: "27",
    code: "za",
    flag: "https://flagsapi.com/ZA/flat/64.png",
    currency: {
      sign: "R",
      short: "ZAR",
      long: "Rand",
      description: "South African rand",
    },
  },
  {
    country: "Spain",
    dialing_code: "34",
    code: "es",
    flag: "https://flagsapi.com/ES/flat/64.png",
    currency: {
      sign: "€",
      short: "EUR",
      long: "Euro",
      description: "Euro",
    },
  },
  {
    country: "Tanzania",
    dialing_code: "255",
    code: "tz",
    flag: "https://flagsapi.com/TZ/flat/64.png",
    currency: {
      sign: "TZS",
      short: "TZS",
      long: "Shilling",
      description: "Tanzanian shilling",
    },
  },
  {
    country: "Togo",
    dialing_code: "228",
    code: "tg",
    flag: "https://flagsapi.com/TG/flat/64.png",
    currency: {
      sign: "CFA",
      short: "XOF",
      long: "CFA franc",
      description: "West African CFA franc",
    },
  },
  {
    country: "United Arab Emirates",
    dialing_code: "971",
    code: "ae",
    flag: "https://flagsapi.com/AE/flat/64.png",
    currency: {
      sign: "د.إ",
      short: "AED",
      long: "Dirham",
      description: "United Arab Emirates Dirham",
    },
  },
  {
    country: "United Kingdom",
    dialing_code: "44",
    code: "gb",
    flag: "https://flagsapi.com/GB/flat/64.png",
    currency: {
      sign: "£",
      short: "GBP",
      long: "Pound Sterling",
      description: "British Pound Sterling",
    },
  },
  {
    country: "United States of America",
    dialing_code: "1",
    code: "us",
    flag: "https://flagsapi.com/US/flat/64.png",
    currency: {
      sign: "$",
      short: "USD",
      long: "Dollar",
      description: "United States Dollar",
    },
  },
  {
    country: "Zambia",
    dialing_code: "260",
    code: "zm",
    flag: "https://flagsapi.com/ZM/flat/64.png",
    currency: {
      sign: "ZK",
      short: "ZMW",
      long: "Kwacha",
      description: "Zambian Kwacha",
    },
  },
  {
    country: "Zimbabwe",
    dialing_code: "263",
    code: "zw",
    flag: "https://flagsapi.com/ZW/flat/64.png",
    currency: {
      sign: "$",
      short: "ZWL",
      long: "Dollar",
      description: "Zimbabwean Dollar",
    },
  },
];

export default merchantCountries;
